### PR TITLE
Fix hedger done context usage

### PR DESCRIPTION
**Pull request by kconwayinvision**
This fixes an issue where the hedger plugin will prematurely cancel a
request context for a successful call. The standard library
http.Transport wraps the response body in a context aware reader that
causes calls to resp.Body.Read() to fail even if the response was a
success and there is a body to read. This patch adjusts the context
management so that "terminal" response returned by the hedger will
always have an active context.

### CODE REVIEW

**Comment by kconwayinvision** [comment]
It looks like some new linting rules have been enabled that are causing the build to fail even for some code not changed in the PR. Let me know how you folks would like me to resolve those issues.

**Review by ensary — APPROVED** [review]

**Comment by ensary** [comment]
> Let me know how you folks would like me to resolve those issues.

Whichever way you prefer. We did not introduce any changes for a while, so there are 2 options:
* Wait until someone else fixes these
* Fix them right away
Depending on your timeline/availability either way works (at least for me).

**Comment by kconwayinvision** [comment]
I don't mind fixing the issues. https://github.com/asecurityteam/transport/pull/26

I'll rebase and //nolint this PR after #26 is merged.

**Review by ensary — APPROVED** [review]

**Comment by kconwayinvision** [comment]
Checking in. Is there anything I need to do before this is good to merge+tag?

**Comment by ensary** [comment]
> Checking in. Is there anything I need to do before this is good to merge+tag?

No, sorry for that Kevin, I'll go poke someone to get more approvals...

**Review by akhalina — APPROVED** [review]

**Pull request merged**
